services:
  mariadb:
    tty: true
    container_name: mariadb
    image: mariadb
    ports:
      - 8306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./docker/mysql_init:/docker-entrypoint-initdb.d
      - aicu-db:/var/lib/mysql
    networks:
      - aicu
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-proot'
      retries: 3
      timeout: 5s
  app:
    tty: true
    container_name: app
    hostname: aicu.local
    build:
        dockerfile: ./docker/Dockerfile
        secrets:
          - CHATGPT_API_KEY
    ports:
        - 8080:80
        - 8443:443
    volumes:
      - aicu-wp:/var/www/html
      - ./:/var/www/html/wp-content/mu-plugins/aiccessibility
      - ./docker/files/wordpress/mu-autoload.php:/var/www/html/wp-content/mu-plugins/mu-autoload.php
    secrets:
      - CHATGPT_API_KEY
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - aicu
networks:
  aicu:
    driver: bridge
volumes:
  aicu-db:
    driver: local
  aicu-wp:
    driver: local
secrets:
  CHATGPT_API_KEY:
    file: ./docker/secrets/CHATGPT_API_KEY
